Working git-protecc branch remove

diff --git a/bin/git-protecc b/bin/git-protecc
--- a/bin/git-protecc
+++ b/bin/git-protecc
@@ -1,9 +1,6 @@
 #!/usr/bin/env bash
-#
-#
 
 ARGS=($@)
-
 NPM_GLOBAL_PATH="$(npm config get prefix)"
 
 is_git_repo() {
@@ -16,9 +13,9 @@ info() {
   echo "execute on a git repository"
   echo ""
   echo "commands:"
-  echo "  branch                            list all protected branches"
-  echo "  branch add <branch1> <branch2>    add branch to protected branches"
-  echo "  branch remove <branch1>           remove branch from protected branches"
+  echo "  branch                   list all protected branches"
+  echo "  branch add <branch>      add branch to protected branches"
+  echo "  branch remove <branch>   remove branch from protected branches"
 }
 
 check_args() {
@@ -46,6 +43,10 @@ check_args() {
     add_protected_branch ${ARGS[*]:2}
     protected_branches
     exit 0
+  elif [ "${ARGS[*]:0:2}" = "branch remove" ]; then
+    remove_protected_branch ${ARGS[*]:2}
+    protected_branches
+    exit 0
   else
     echo "Invalid command git-protecc ${ARGS[*]}"
     echo ""
@@ -55,7 +56,7 @@ check_args() {
 }
 
 protected_branches() {
-  echo "$(git config --get-all git-protecc.branch)"
+  echo -e $(git config --get-all git-protecc.branch)
 }
 
 is_existing_git_branch() {
@@ -76,6 +77,19 @@ git_branch_exist() {
   done
 }
 
+protected_branch_exist() {
+  branch=($@)
+  for branch in "${branch[@]}"
+  do
+    if ! is_protected_branch $branch; then
+      echo "Invalid git-protecc branch $branch"
+      echo ""
+      info
+      exit 1
+    fi
+  done
+}
+
 is_protected_branch() {
   $(git config --get-all git-protecc.branch | grep $1$ > /dev/null 2>&1)
 }
@@ -87,6 +101,17 @@ add_protected_branch() {
   do
     if ! is_protected_branch $branch; then
       git config --add git-protecc.branch $branch
+    fi
+  done
+}
+
+remove_protected_branch() {
+  protected_branch_exist $@
+
+  for branch in $@
+  do
+    if is_protected_branch $branch; then
+      git config --unset git-protecc.branch $branch
     fi
   done
 }
